no t2

diff --git a/.github/workflows/track_visitors.yml b/.github/workflows/track_visitors.yml
--- a/.github/workflows/track_visitors.yml
+++ b/.github/workflows/track_visitors.yml
@@ -38,11 +38,11 @@ jobs:
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git config --global user.name "github-actions[bot]"
           if [ -n "$(git status --porcelain)" ]; then
-            git stash
-            git pull origin ${{ github.ref }} --rebase
-            git stash pop || true  # Ignore error if no stash entries to pop
+            git stash || true
+            git pull origin ${{ github.ref }} --rebase || true
+            git stash pop || true  # Ignore error if no stash entries to pop or pull fails
           else
-            git pull origin ${{ github.ref }} --rebase
+            git pull origin ${{ github.ref }} --rebase || true  # Ignore error if pull fails
           fi
           git add -A  # Add all changes including untracked files
           if git diff-index --quiet HEAD --; then
